/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppFooter: typeof import('./../src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./../src/components/AppHeader.vue')['default']
    ClusterSelector: typeof import('./../src/components/ClusterSelector.vue')['default']
    ConnectWallet: typeof import('./../src/components/ConnectWallet.vue')['default']
    CopyToClipboard: typeof import('./../src/components/CopyToClipboard.vue')['default']
    DarkThemeToggle: typeof import('./../src/components/DarkThemeToggle.vue')['default']
    HomeNav: typeof import('./../src/components/Home/HomeNav.vue')['default']
    IAppDiscord: typeof import('~icons/app/discord')['default']
    IAppSmartContract: typeof import('~icons/app/smart-contract')['default']
    IAppTelegram: typeof import('~icons/app/telegram')['default']
    IAppTwitter: typeof import('~icons/app/twitter')['default']
    MobileMenu: typeof import('./../src/components/Menu/MobileMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./../src/components/Sidebar/Sidebar.vue')['default']
    SidebarCopyrights: typeof import('./../src/components/Sidebar/SidebarCopyrights.vue')['default']
    SidebarFooter: typeof import('./../src/components/Sidebar/SidebarFooter.vue')['default']
    SidebarHeader: typeof import('./../src/components/Sidebar/SidebarHeader.vue')['default']
    SidebarNavigation: typeof import('./../src/components/Sidebar/SidebarNavigation.vue')['default']
    SidebarSocial: typeof import('./../src/components/Sidebar/SidebarSocial.vue')['default']
    SocialLinks: typeof import('./../src/components/SocialLinks.vue')['default']
    SwapCard: typeof import('./../src/components/Swap/SwapCard.vue')['default']
    SwapContent: typeof import('./../src/components/Swap/SwapContent.vue')['default']
    TransferCard: typeof import('./../src/components/Transfer/TransferCard.vue')['default']
    TransferContent: typeof import('./../src/components/Transfer/TransferContent.vue')['default']
  }
}
