/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppDescription: typeof import('./../src/components/AppDescription.vue')['default']
    AppDescriptionTop: typeof import('./../src/components/AppDescriptionTop.vue')['default']
    AppHeader: typeof import('./../src/components/AppHeader.vue')['default']
    CertificateStatus: typeof import('./../src/components/PolicyCard/CertificateStatus.vue')['default']
    ClusterSelector: typeof import('./../src/components/ClusterSelector.vue')['default']
    ConnectWallet: typeof import('./../src/components/ConnectWallet.vue')['default']
    CopyToClipboard: typeof import('./../src/components/CopyToClipboard.vue')['default']
    CreateCertificateBtn: typeof import('./../src/components/PolicyCard/CreateCertificateBtn.vue')['default']
    CreateSwapCard: typeof import('./../src/components/pools/CreateSwapCard.vue')['default']
    DarkThemeToggle: typeof import('./../src/components/DarkThemeToggle.vue')['default']
    IAppCertificate: typeof import('~icons/app/certificate')['default']
    IAppDiscord: typeof import('~icons/app/discord')['default']
    IAppTelegram: typeof import('~icons/app/telegram')['default']
    IAppTwitterX: typeof import('~icons/app/twitter-x')['default']
    MintTokenA: typeof import('./../src/components/MintTokenA.vue')['default']
    MobileMenu: typeof import('./../src/components/Menu/MobileMenu.vue')['default']
    PasswordProtect: typeof import('./../src/components/PasswordProtect.vue')['default']
    PolicyCard: typeof import('./../src/components/PolicyCard/PolicyCard.vue')['default']
    PolicyCardView: typeof import('./../src/components/PolicyCard/PolicyCardView.vue')['default']
    PolicyInfoDialog: typeof import('./../src/components/PolicyCard/PolicyInfoDialog.vue')['default']
    PolicyInfoView: typeof import('./../src/components/PolicyCard/PolicyInfoView.vue')['default']
    PoolsList: typeof import('./../src/components/pools/PoolsList.vue')['default']
    PoolsListItem: typeof import('./../src/components/pools/PoolsListItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectPool: typeof import('./../src/components/Swap/SelectPool.vue')['default']
    SelectToken: typeof import('./../src/components/SelectToken.vue')['default']
    Sidebar: typeof import('./../src/components/Sidebar/Sidebar.vue')['default']
    SidebarCopyrights: typeof import('./../src/components/Sidebar/SidebarCopyrights.vue')['default']
    SidebarFooter: typeof import('./../src/components/Sidebar/SidebarFooter.vue')['default']
    SidebarHeader: typeof import('./../src/components/Sidebar/SidebarHeader.vue')['default']
    SidebarNavigation: typeof import('./../src/components/Sidebar/SidebarNavigation.vue')['default']
    SocialLinks: typeof import('./../src/components/SocialLinks.vue')['default']
    StakeCard: typeof import('./../src/components/Stake/StakeCard.vue')['default']
    SwapCard: typeof import('./../src/components/Swap/SwapCard.vue')['default']
    TransferCard: typeof import('./../src/components/Transfer/TransferCard.vue')['default']
    WarningDisclaimer: typeof import('./../src/components/WarningDisclaimer.vue')['default']
  }
}
