/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./../src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./../src/components/AppHeader.vue')['default']
    ClusterSelector: typeof import('./../src/components/ClusterSelector.vue')['default']
    ConnectWallet: typeof import('./../src/components/ConnectWallet.vue')['default']
    CopyToClipboard: typeof import('./../src/components/CopyToClipboard.vue')['default']
    CreateCertificateBtn: typeof import('./../src/components/CreateCertificateBtn.vue')['default']
    CreateCertificateDialog: typeof import('./../src/components/CreateCertificateDialog.vue')['default']
    DarkThemeToggle: typeof import('./../src/components/DarkThemeToggle.vue')['default']
    HeaderCertificate: typeof import('./../src/components/Header/HeaderCertificate.vue')['default']
    HeaderNotifications: typeof import('./../src/components/Header/HeaderNotifications.vue')['default']
    HomeNav: typeof import('./../src/components/Home/HomeNav.vue')['default']
    IAppCertificate: typeof import('~icons/app/certificate')['default']
    IAppDiscord: typeof import('~icons/app/discord')['default']
    IAppTelegram: typeof import('~icons/app/telegram')['default']
    IAppTwitter: typeof import('~icons/app/twitter')['default']
    MobileMenu: typeof import('./../src/components/Menu/MobileMenu.vue')['default']
    PolicyCard: typeof import('./../src/components/PolicyCard.vue')['default']
    PolicyInfoCard: typeof import('./../src/components/PolicyInfoCard.vue')['default']
    PolicyInfoDialog: typeof import('./../src/components/PolicyInfoDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectToken: typeof import('./../src/components/SelectToken.vue')['default']
    Sidebar: typeof import('./../src/components/Sidebar/Sidebar.vue')['default']
    SidebarCopyrights: typeof import('./../src/components/Sidebar/SidebarCopyrights.vue')['default']
    SidebarFooter: typeof import('./../src/components/Sidebar/SidebarFooter.vue')['default']
    SidebarHeader: typeof import('./../src/components/Sidebar/SidebarHeader.vue')['default']
    SidebarNavigation: typeof import('./../src/components/Sidebar/SidebarNavigation.vue')['default']
    SocialLinks: typeof import('./../src/components/SocialLinks.vue')['default']
    StakeCard: typeof import('./../src/components/Stake/StakeCard.vue')['default']
    StakeContent: typeof import('./../src/components/Stake/StakeContent.vue')['default']
    SwapCard: typeof import('./../src/components/Swap/SwapCard.vue')['default']
    SwapContent: typeof import('./../src/components/Swap/SwapContent.vue')['default']
    TransferCard: typeof import('./../src/components/Transfer/TransferCard.vue')['default']
    TransferContent: typeof import('./../src/components/Transfer/TransferContent.vue')['default']
    ZkpRequestDialog: typeof import('./../src/components/ZkpRequestDialog.vue')['default']
  }
}
