/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category SwapPToA
 * @category generated
 */
export type SwapPToAInstructionArgs = {
  destinationTokenAmount: beet.bignum
  maximumPoolTokenAmount: beet.bignum
}
/**
 * @category Instructions
 * @category SwapPToA
 * @category generated
 */
export const swapPToAStruct = new beet.BeetArgsStruct<
  SwapPToAInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['destinationTokenAmount', beet.u64],
    ['maximumPoolTokenAmount', beet.u64],
  ],
  'SwapPToAInstructionArgs'
)
/**
 * Accounts required by the _swapPToA_ instruction
 *
 * @property [_writable_] sourceTokenA
 * @property [_writable_] tokenA
 * @property [_writable_] tokenB
 * @property [_writable_] poolMint
 * @property [_writable_] poolToken
 * @property [_writable_] poolFee
 * @property [] tokenSwap
 * @property [] tokenSwapAuthority
 * @property [] authority
 * @property [] tokenSwapProgram
 * @category Instructions
 * @category SwapPToA
 * @category generated
 */
export type SwapPToAInstructionAccounts = {
  sourceTokenA: web3.PublicKey
  tokenA: web3.PublicKey
  tokenB: web3.PublicKey
  poolMint: web3.PublicKey
  poolToken: web3.PublicKey
  poolFee: web3.PublicKey
  tokenSwap: web3.PublicKey
  tokenSwapAuthority: web3.PublicKey
  authority: web3.PublicKey
  tokenProgram?: web3.PublicKey
  tokenSwapProgram: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const swapPToAInstructionDiscriminator = [
  146, 164, 231, 118, 63, 216, 127, 101,
]

/**
 * Creates a _SwapPToA_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category SwapPToA
 * @category generated
 */
export function createSwapPToAInstruction(
  accounts: SwapPToAInstructionAccounts,
  args: SwapPToAInstructionArgs,
  programId = new web3.PublicKey('GEKHqpoYKtPZusV2CS7fjcfStszxDUGsnuZXonxd5tba')
) {
  const [data] = swapPToAStruct.serialize({
    instructionDiscriminator: swapPToAInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.sourceTokenA,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenA,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenB,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.poolMint,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.poolToken,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.poolFee,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenSwap,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenSwapAuthority,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.authority,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenSwapProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
